.PHONY: clean

proj3.pdf: proj3.ps
	ps2pdf -sPAPERSIZE=a4 proj3.ps 

proj3.ps: proj3.dvi
	dvips proj3.dvi

proj3.dvi: proj3.tex
	latex proj3.tex
	latex proj3.tex

clean:
	rm -f *.ps
	rm -f *.dvi
	rm -f *.aux
	rm -f *.out  
	rm -f *.log
