INSERT INTO stop (name, type, lat, long) VALUES ('stop1', 'train', cast('10' as double precision), cast('20' as double precision));
INSERT INTO stop (name, type, lat, long) VALUES ('stop2', 'train', cast('30' as double precision), cast('-10' as double precision));
INSERT INTO stop (name, type, lat, long) VALUES ('stop3', 'bus', cast('20' as double precision), cast('-20' as double precision));
INSERT INTO stop (name, type, lat, long) VALUES ('stop4', 'bus', cast('5' as double precision), cast('6' as double precision));
INSERT INTO stop (name, type, lat, long) VALUES ('stop5', 'tram', cast('4' as double precision), cast('-8' as double precision));
INSERT INTO stop (name, type, lat, long) VALUES ('stop6', 'tram', cast('18' as double precision), cast('-14' as double precision));
INSERT INTO stop (name, type, lat, long) VALUES ('stop7', 'plane', cast('60' as double precision), cast('80' as double precision));
INSERT INTO stop (name, type, lat, long) VALUES ('stop8', 'plane', cast('-30' as double precision), cast('50' as double precision));
INSERT INTO stop (name, type, lat, long) VALUES ('stop9', 'plane', cast('-10' as double precision), cast('40' as double precision));
INSERT INTO stop (name, type, lat, long) VALUES ('stop10', 'train', cast('0' as double precision), cast('0' as double precision));
INSERT INTO stop (name, type, lat, long) VALUES ('stop11', 'bus', cast('0' as double precision), cast('0' as double precision));
INSERT INTO stop (name, type, lat, long) VALUES ('stop12', 'tram', cast('0' as double precision), cast('0' as double precision));

-- SELECT * FROM stop;

INSERT INTO vehicle (name, type, lat, long) VALUES ('bus_name1', 'bus', cast('0' as double precision), cast('0' as double precision));
INSERT INTO vehicle (name, type, lat, long) VALUES ('bus_name2', 'bus', cast('0' as double precision), cast('0' as double precision));
INSERT INTO vehicle (name, type, lat, long) VALUES ('train_name1', 'train', cast('0' as double precision), cast('0' as double precision));
INSERT INTO vehicle (name, type, lat, long) VALUES ('train_name2', 'train', cast('0' as double precision), cast('0' as double precision));

-- SELECT * FROM vehicle;

INSERT INTO vehicle_section (name, type, index, vehicle_id) VALUES ('bus_section_name1', 'bus', cast('0' as integer), cast('1' as integer));
INSERT INTO vehicle_section (name, type, index, vehicle_id) VALUES ('bus_section_name2', 'bus', cast('0' as integer), cast('2' as integer));
INSERT INTO vehicle_section (name, type, index, vehicle_id) VALUES ('train_section_name1', 'train', cast('0' as integer), cast('3' as integer));
INSERT INTO vehicle_section (name, type, index, vehicle_id) VALUES ('train_section_name2', 'train', cast('1' as integer), cast('3' as integer));
INSERT INTO vehicle_section (name, type, index, vehicle_id) VALUES ('train_section_name3', 'train', cast('0' as integer), cast('4' as integer));

-- SELECT * FROM vehicle_section;

INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('0' as integer), cast('1' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('1' as integer), cast('1' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('2' as integer), cast('1' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('3' as integer), cast('1' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('4' as integer), cast('1' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('5' as integer), cast('1' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('6' as integer), cast('1' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('7' as integer), cast('1' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('8' as integer), cast('1' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('9' as integer), cast('1' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('10' as integer), cast('1' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('11' as integer), cast('1' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('12' as integer), cast('1' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('13' as integer), cast('1' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('14' as integer), cast('1' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('15' as integer), cast('1' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('16' as integer), cast('1' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('17' as integer), cast('1' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('18' as integer), cast('1' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('19' as integer), cast('1' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('20' as integer), cast('1' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('21' as integer), cast('1' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('22' as integer), cast('1' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('23' as integer), cast('1' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('24' as integer), cast('1' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('25' as integer), cast('1' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('26' as integer), cast('1' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('27' as integer), cast('1' as integer));

INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('0' as integer), cast('2' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('1' as integer), cast('2' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('2' as integer), cast('2' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('3' as integer), cast('2' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('4' as integer), cast('2' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('5' as integer), cast('2' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('6' as integer), cast('2' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('7' as integer), cast('2' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('8' as integer), cast('2' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('9' as integer), cast('2' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('10' as integer), cast('2' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('11' as integer), cast('2' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('12' as integer), cast('2' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('13' as integer), cast('2' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('14' as integer), cast('2' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('15' as integer), cast('2' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('16' as integer), cast('2' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('17' as integer), cast('2' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('18' as integer), cast('2' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('19' as integer), cast('2' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('20' as integer), cast('2' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('21' as integer), cast('2' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('22' as integer), cast('2' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('23' as integer), cast('2' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('24' as integer), cast('2' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('25' as integer), cast('2' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('26' as integer), cast('2' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('27' as integer), cast('2' as integer));

INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('0' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('1' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('2' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('3' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('4' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('5' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('6' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('7' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('8' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('9' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('10' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('11' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('12' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('13' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('14' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('15' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('16' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('17' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('18' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('19' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('20' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('21' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('22' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('23' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('24' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('25' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('26' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('27' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('28' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('29' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('30' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('31' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('32' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('33' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('34' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('35' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('36' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('37' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('38' as integer), cast('3' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('39' as integer), cast('3' as integer));

INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('0' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('1' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('2' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('3' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('4' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('5' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('6' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('7' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('8' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('9' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('10' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('11' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('12' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('13' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('14' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('15' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('16' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('17' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('18' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('19' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('20' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('21' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('22' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('23' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('24' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('25' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('26' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('27' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('28' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('29' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('30' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('31' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('32' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('33' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('34' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('35' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('36' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('37' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('38' as integer), cast('4' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('39' as integer), cast('4' as integer));

INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('0' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('1' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('2' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('3' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('4' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('5' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('6' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('7' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('8' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('9' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('10' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('11' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('12' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('13' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('14' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('15' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('16' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('17' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('18' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('19' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('20' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('21' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('22' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('23' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('24' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('25' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('26' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('27' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('28' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('29' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('30' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('31' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('32' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('33' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('34' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('35' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('36' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('37' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('38' as integer), cast('5' as integer));
INSERT INTO vehicle_section_seat (index, vehicle_section_id) VALUES (cast('39' as integer), cast('5' as integer));

-- SELECT * FROM vehicle_section_seat;
INSERT INTO connection (carrier, flags, vehicle_id) VALUES (7, cast('11111110' as bit(8)), cast('1' as integer));
INSERT INTO connection (carrier, flags, vehicle_id) VALUES (7, cast('00000100' as bit(8)), cast('2' as integer));
INSERT INTO connection (carrier, flags, vehicle_id) VALUES (8, cast('11111000' as bit(8)), cast('3' as integer));
INSERT INTO connection (carrier, flags, vehicle_id) VALUES (8, cast('00000110' as bit(8)), cast('4' as integer));

-- SELECT * FROM connection;

INSERT INTO "user" (username, password, email, phone, full_name, role, carrier) VALUES ('admin1', 'pbkdf2:sha256:50000$YDsqnEcN$6c2620de0d1ea5bd10522759f6caeeed71d58700bfd8103b85a855bf64becc87', 'email1@noreply.com', '111111111', 'Name Namename1', 'administator', NULL);
INSERT INTO "user" (username, password, email, phone, full_name, role, carrier) VALUES ('admin2', 'pbkdf2:sha256:50000$Mqrj21nx$adad4a9866f4c32975226151db88e56166b7bba7f345bf842ce161c9612979df', 'email2@noreply.com', '222222222', 'Name Namename2', 'administator', NULL);
INSERT INTO "user" (username, password, email, phone, full_name, role, carrier) VALUES ('carrier1', 'pbkdf2:sha256:50000$1AqfZNZ0$424ea21bdbcc9f8ef459de35c0761873fae2ba7f81ce79c03ca799108da8bdea', 'email3@noreply.com', '333333333', 'Name Namename3', 'carrier', NULL);
INSERT INTO "user" (username, password, email, phone, full_name, role, carrier) VALUES ('carrier2', 'pbkdf2:sha256:50000$3NKrYSBJ$cbaed33ada7a7951605e9fb28af0f9833b0321db60d023f3ff416275ef0fb710', 'email4@noreply.com', '444444444', 'Name Namename4', 'carrier', NULL);
INSERT INTO "user" (username, password, email, phone, full_name, role, carrier) VALUES ('personnel1', 'pbkdf2:sha256:50000$geltdO7r$d836d04c6bc7cf4a8805f95c8031eaa2d11bb3a7997f8fff838f76aed1bdc207', 'email5@noreply.com', '555555555', 'Name Namename5', 'personnel', cast('3' as integer));
INSERT INTO "user" (username, password, email, phone, full_name, role, carrier) VALUES ('personnel2', 'pbkdf2:sha256:50000$Fkyg1t9Z$ec894433faaec53e04504514937446c9ba7809f355e5ed241f74b4173ee25076', 'email6@noreply.com', '666666666', 'Name Namename6', 'personnel', cast('3' as integer));
INSERT INTO "user" (username, password, email, phone, full_name, role, carrier) VALUES ('personnel3', 'pbkdf2:sha256:50000$VsE64Zyj$04758b4f6a52fc100ac339f1a5cae541219c1b5b0a264b8cd203b86035d3f120', 'email7@noreply.com', '777777777', 'Name Namename7', 'personnel', cast('4' as integer));
INSERT INTO "user" (username, password, email, phone, full_name, role, carrier) VALUES ('registered1', 'pbkdf2:sha256:50000$ttKsvoCT$dc01311eefbaa621873862fc4fb096c4a8927a8614653df25677f838a970f487', 'email8@noreply.com', '888888888', 'Name Namename8', 'registered', NULL);
INSERT INTO "user" (username, password, email, phone, full_name, role, carrier) VALUES ('registered2', 'pbkdf2:sha256:50000$nUepFWiN$50f65d799790079ddd230a931b36fe5777e4042963a3c7bc239d6097c069ab43', 'email9@noreply.com', '999999999', 'Name Namename9', 'registered', NULL);
INSERT INTO "user" (username, password, email, phone, full_name, role, carrier) VALUES (NULL, NULL, 'email10@noreply.com', NULL, NULL, 'unregistered', NULL);
INSERT INTO "user" (username, password, email, phone, full_name, role, carrier) VALUES (NULL, NULL, 'email11@noreply.com', NULL, NULL, 'unregistered', NULL);

-- SELECT * FROM "user";

INSERT INTO reservation (status, cost, start_index, end_index, seats, connection_id, user_id, reservation_date) VALUES ('approved', cast('123' as integer), cast('0' as integer), cast('2' as integer), '{0, 1, 2, 3}', cast('1' as integer), cast('5' as integer), DATE '2021-11-19');
INSERT INTO reservation (status, cost, start_index, end_index, seats, connection_id, user_id, reservation_date) VALUES ('approved', cast('321' as integer), cast('1' as integer), cast('2' as integer), '{10, 11, 12}', cast('1' as integer), cast('6' as integer), DATE '2021-11-20');
INSERT INTO reservation (status, cost, start_index, end_index, seats, connection_id, user_id, reservation_date) VALUES ('approved', cast('234' as integer), cast('0' as integer), cast('2' as integer), '{0, 1, 2, 3}', cast('2' as integer), cast('12' as integer), DATE '2021-11-21');
INSERT INTO reservation (status, cost, start_index, end_index, seats, connection_id, user_id, reservation_date) VALUES ('approved', cast('432' as integer), cast('0' as integer), cast('2' as integer), '{0, 1, 2, 3}', cast('3' as integer), cast('13' as integer), DATE '2021-11-19');
INSERT INTO reservation (status, cost, start_index, end_index, seats, connection_id, user_id, reservation_date) VALUES ('approved', cast('345' as integer), cast('0' as integer), cast('2' as integer), '{10, 11, 12}', cast('3' as integer), cast('14' as integer), DATE '2021-11-20');
INSERT INTO reservation (status, cost, start_index, end_index, seats, connection_id, user_id, reservation_date) VALUES ('pending', cast('543' as integer), cast('0' as integer), cast('2' as integer), '{0, 1, 2, 3}', cast('4' as integer), cast('15' as integer), DATE '2021-11-21');

-- SELECT * FROM reservation;

-- bussin
INSERT INTO stop_timed (stop_id, departure, index, connection_id) VALUES (cast('3' as integer), TIME '10:15:00', cast('0' as integer), cast('1' as integer));
INSERT INTO stop_timed (stop_id, departure, index, connection_id) VALUES (cast('4' as integer), TIME '10:20:00', cast('1' as integer), cast('1' as integer));
INSERT INTO stop_timed (stop_id, departure, index, connection_id) VALUES (cast('11' as integer), TIME '10:30:00', cast('2' as integer), cast('1' as integer));

INSERT INTO stop_timed (stop_id, departure, index, connection_id) VALUES (cast('11' as integer), TIME '10:45:00', cast('0' as integer), cast('2' as integer));
INSERT INTO stop_timed (stop_id, departure, index, connection_id) VALUES (cast('3' as integer), TIME '10:50:00', cast('1' as integer), cast('2' as integer));
INSERT INTO stop_timed (stop_id, departure, index, connection_id) VALUES (cast('4' as integer), TIME '10:55:00', cast('2' as integer), cast('2' as integer));

-- trainin
INSERT INTO stop_timed (stop_id, departure, index, connection_id) VALUES (cast('1' as integer), TIME '11:15:00', cast('0' as integer), cast('3' as integer));
INSERT INTO stop_timed (stop_id, departure, index, connection_id) VALUES (cast('2' as integer), TIME '11:20:00', cast('1' as integer), cast('3' as integer));
INSERT INTO stop_timed (stop_id, departure, index, connection_id) VALUES (cast('10' as integer), TIME '11:30:00', cast('2' as integer), cast('3' as integer));

INSERT INTO stop_timed (stop_id, departure, index, connection_id) VALUES (cast('10' as integer), TIME '11:45:00', cast('0' as integer), cast('4' as integer));
INSERT INTO stop_timed (stop_id, departure, index, connection_id) VALUES (cast('1' as integer), TIME '11:50:00', cast('1' as integer), cast('4' as integer));
INSERT INTO stop_timed (stop_id, departure, index, connection_id) VALUES (cast('2' as integer), TIME '11:55:00', cast('2' as integer), cast('4' as integer));
-- SELECT * FROM stop_timed;